BanhHang_MVC/Controllers/DanhSachSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BanhHang_MVC;

namespace BanhHang_MVC.Controllers
{
    public class DanhSachSanPhamController : Controller
    {
        private WebBanHangEntities_1 db = new WebBanHangEntities_1();

        // GET: DanhSachSanPham
        public ActionResult Index()
        {
            return View(db.DanhSachSanPham.ToList());
        }

        // GET: DanhSachSanPham/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhSachSanPham danhSachSanPham = db.DanhSachSanPham.Find(id);
            if (danhSachSanPham == null)
            {
                return HttpNotFound();
            }
            return View(danhSachSanPham);
        }

        // GET: DanhSachSanPham/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DanhSachSanPham/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,ten,hinhanh,dongia,madm")] DanhSachSanPham danhSachSanPham)
        {
            if (ModelState.IsValid)
            {
                db.DanhSachSanPham.Add(danhSachSanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(danhSachSanPham);
        }

        // GET: DanhSachSanPham/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhSachSanPham danhSachSanPham = db.DanhSachSanPham.Find(id);
            if (danhSachSanPham == null)
            {
                return HttpNotFound();
            }
            return View(danhSachSanPham);
        }

        // POST: DanhSachSanPham/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,ten,hinhanh,dongia,madm")] DanhSachSanPham danhSachSanPham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(danhSachSanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(danhSachSanPham);
        }

        // GET: DanhSachSanPham/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhSachSanPham danhSachSanPham = db.DanhSachSanPham.Find(id);
            if (danhSachSanPham == null)
            {
                return HttpNotFound();
            }
            return View(danhSachSanPham);
        }

        // POST: DanhSachSanPham/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DanhSachSanPham danhSachSanPham = db.DanhSachSanPham.Find(id);
            db.DanhSachSanPham.Remove(danhSachSanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BanhHang_MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanhHang_MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BanhHang_MVC/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanhHang_MVC.Controllers
{
    public class TrangChuController : Controller
    {
        // GET: TrangChu
        private WebBanHangEntities_1 db = new WebBanHangEntities_1();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            DanhSachSanPham danhsachsanpham = db.DanhSachSanPham.Find(id);
            if (danhsachsanpham == null)
            {
                return HttpNotFound();
            }
            return View(danhsachsanpham);
        }
    }
}

BanhHang_MVC/Views/DanhSachSanPham/Create.cshtml
@model BanhHang_MVC.DanhSachSanPham

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DanhSachSanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hinhanh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hinhanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hinhanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dongia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dongia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dongia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.madm, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.madm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.madm, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BanhHang_MVC/Views/DanhSachSanPham/Delete.cshtml
@model BanhHang_MVC.DanhSachSanPham

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DanhSachSanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinhanh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hinhanh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dongia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dongia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.madm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.madm)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BanhHang_MVC/Views/DanhSachSanPham/Details.cshtml
@model BanhHang_MVC.DanhSachSanPham

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DanhSachSanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinhanh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hinhanh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dongia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dongia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.madm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.madm)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BanhHang_MVC/Views/DanhSachSanPham/Edit.cshtml
@model BanhHang_MVC.DanhSachSanPham

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DanhSachSanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.ten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hinhanh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hinhanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hinhanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dongia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dongia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dongia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.madm, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.madm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.madm, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BanhHang_MVC/Views/DanhSachSanPham/Index.cshtml
@model IEnumerable<BanhHang_MVC.DanhSachSanPham>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ten)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.hinhanh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dongia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.madm)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ten)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.hinhanh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dongia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.madm)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

BanhHang_MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BanhHang_MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BanhHang_MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

BanhHang_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BanhHang_MVC/Views/TrangChu/index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<html>
<head runat="server">
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
    <link rel="stylesheet" type="text/css" href="~/Content/style.css" />
    <!--[if IE 6]>
    <link rel="stylesheet" type="text/css" href="css/iecss.css" />
    <![endif]-->
    <script type="text/javascript" src="~/Scripts/boxOver.js"></script>
</head>
<body>
    <form id="form1">
        <div id="main_container">
            <div class="top_bar">
                <div class="top_search">
                    <div class="search_text"><a href="#">Advanced Search</a></div>
                    <input type="text" class="search_input" name="search" />
                    <input type="image" src="/images/search.gif" class="search_bt" />
                </div>
                <div class="languages">
                    <div class="lang_text">Languages:</div>
                    <a href="#" class="lang"><img src="/images/en.gif" alt="" border="0" /></a> <a href="#" class="lang">
                        <img src="/images/de.gif" alt="" border="0" />
                    </a>
                </div>
            </div>
            <div id="header">
                <div id="logo">
                    <a href="#"><img src="/images/logo.png" alt="" border="0" width="237" height="140" /></a>
                </div>
                <div class="oferte_content">
                    <div class="top_divider"><img src="/images/header_divider.png" alt="" width="1" height="164" /></div>
                    <div class="oferta">
                        <div class="oferta_content">
                            <img src="/images/laptop.png" width="94" height="92" alt="" border="0" class="oferta_img" />
                            <div class="oferta_details">
                                <div class="oferta_title">Samsung GX 2004 LM</div>
                                <div class="oferta_text">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                                </div>
                                <a href="details.html" class="details">details</a>
                            </div>
                        </div>
                        <div class="oferta_pagination">
                            <span class="current">1</span> <a href="#">2</a> <a href="#">3</a> <a href="#">4</a> <a href="#">5</a>
                        </div>
                    </div>
                    <div class="top_divider"><img src="/images/header_divider.png" alt="" width="1" height="164" /></div>
                </div>
                <!-- end of oferte_content-->
            </div>
            <div id="main_content">
                <div id="menu_tab">
                    <div class="left_menu_corner"></div>
                    <ul class="menu">
                        <li><a href="#" class="nav1"> Home</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="nav2">Products</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="nav3">Specials</a></li>
                        <li class="divider"></li>
                        <li><a href="pageLOGIN.aspx" class="nav4">My account</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="nav4">Sign Up</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="nav5">Shipping</a></li>
                        <li class="divider"></li>
                        <li><a href="contact.html" class="nav6">Contact Us</a></li>
                        <li class="divider"></li>
                        <li class="currencies">
                            Currencies
                            <select>
                                <option>US Dollar</option>
                                <option>Euro</option>
                            </select>
                        </li>
                    </ul>
                    <div class="right_menu_corner"></div>
                </div>
                <!-- end of menu tab -->
                <div class="crumb_navigation"> Navigation: <span class="current">Home</span> </div>
                <div class="left_content">
                    <div class="title_box">Categories</div>
                    <ul class="left_menu">
                        @foreach (var item in new WebBanHangEntities_1().DanhMucSanPham)
                        {
                            <li class="odd">
                                <a href="#"> @Html.DisplayFor(modelItem => item.ten)</a>
                            </li>
                        }
                    </ul>
                    <div class="title_box">Special Products</div>
                    <div class="border_box">
                        <div class="product_title"><a href="details.html">Motorola 156 MX-VL</a></div>
                        <div class="product_img">
                            <a href="details.html">
                                <img src="/images/laptop.png" alt="" border="0" />
                            </a>
                        </div>
                        <div class="prod_price"><span class="reduce">350$</span> <span class="price">270$</span></div>
                    </div>
                    <div class="title_box">Newsletter</div>
                    <div class="border_box">
                        <input type="text" name="newsletter" class="newsletter_input" value="your email" />
                        <a href="#" class="join">join</a>
                    </div>
                    <div class="banner_adds"> <a href="#"><img src="/images/bann2.jpg" alt="" border="0" /></a> </div>
                </div>
                <!-- end of left content -->
                <div class="center_content">
                    <div class="center_title_bar">Latest Products</div>
                    @foreach (var item in new WebBanHangEntities_1().DanhSachSanPham)
                    {
                        <div class="prod_box">
                            <div class="top_prod_box"></div>
                            <div class="center_prod_box">
                                <div class="product_title">
                                    @Html.ActionLink(item.ten, "detail", new { id = item.id })
                                </div>
                                <div class="product_img">
                                    <a href='@Url.Action("detail", "TrangChu", new { id = item.id })'>
                                        <img src="~/images/@Html.DisplayFor(modelItem => item.hinhanh)" alt=""
                                             border="0" width="100px" height="100px" />
                                    </a>
                                </div>
                                <div class="prod_price">
                                    <span class="reduce">@{int dongiamoi = (int)item.dongia * 115 / 100; @Html.DisplayFor(modelItem => dongiamoi)}</span> <span class="price"> @Html.DisplayFor(modelItem => item.dongia)$ </span>
                                </div>
                            </div>
                            <div class="bottom_prod_box"></div>
                            <div class="prod_details_tab">
                                <a href="#" title="header=[Add to cart] body=[&nbsp;]
 fade=[on]"><img src="/images/cart.gif" alt="" border="0" class="left_bt" /></a>
                                <a href="#" title="header=[Specials] body=[&nbsp;] fade=[on]">
                                    <img src="/images/favs.gif" alt="" border="0" class="left_bt" />
                                </a>
                                <a href="#" title="header=[Gifts] body=[&nbsp;] fade=[on]">
                                    <img src="/images/favorites.gif" alt="" border="0" class="left_bt" />
                                </a>
                                <a href="detail/@item.id" class="prod_details">details</a>
                            </div>
                        </div>
                    }
                </div>
                <!-- end of center content -->
                <div class="right_content">
                    <div class="shopping_cart">
                        <div class="cart_title">Shopping cart</div>
                        <div class="cart_details">
                            3 items <br />
                            <span class="border_cart"></span> Total: <span class="price">350$</span>
                        </div>
                        <div class="cart_icon">
                            <a href="#" title="header=[Checkout] body=[&nbsp;] fade=[on]">
                                <img src="/images/shoppingcart.png" alt="" width="48" height="48" border="0" />
                            </a>
                        </div>
                    </div>
                    <div class="title_box">What’s new</div>
                    <div class="border_box">
                        <div class="product_title"><a href="details.html">Motorola 156 MX-VL</a></div>
                        <div class="product_img"><a href="details.html"><img src="/images/p2.gif" alt="" border="0" /></a></div>
                        <div class="prod_price"><span class="reduce">350$</span> <span class="price">270$</span></div>
                    </div>
                    <div class="title_box">Manufacturers</div>
                    <ul class="left_menu">
                        <li class="odd"><a href="#">Sony</a></li>
                        <li class="even"><a href="#">Samsung</a></li>
                        <li class="odd"><a href="#">Daewoo</a></li>
                        <li class="even"><a href="#">LG</a></li>
                        <li class="odd"><a href="#">Fujitsu Siemens</a></li>
                        <li class="even"><a href="#">Motorola</a></li>
                        <li class="odd"><a href="#">Phillips</a></li>
                        <li class="even"><a href="#">Beko</a></li>
                    </ul>
                    <div class="banner_adds"> <a href="#"><img src="/images/bann1.jpg" alt="" border="0" /></a> </div>
                </div>
                <!-- end of right content -->
            </div>
            <!-- end of main content -->
            <div class="footer">
                <div class="left_footer"> <img src="/images/footer_logo.png" alt="" width="170" height="49" /> </div>
                <div class="center_footer">
                    Template name. All Rights Reserved 2008<br />
                    <a href="http://csscreme.com"><img src="/images/csscreme.jpg" alt="csscreme" border="0" /></a><br />
                    <img src="/images/payment.gif" alt="" />
                </div>
                <div class="right_footer">
                    <a href="#">home</a> <a href="#">about</a> <a href="#">sitemap</a> <a href="#">rss</a> <a href="contact.html">contact us</a>
                </div>
            </div>
        </div>
    </form>
</body>
</html>